if(CONFIG_APP_ZIGBEE_MINIMAL_TEST)
    idf_component_register(
        SRCS
            "app_main.c"
            "event_bus.c"
            "fatal_error.c"
            "input.c"
            "jarzem_ota_project_hooks.c"
            "minimal_app_state.c"
            "status_led.c"
            "storage.c"
            "zigbee_minimal.c"
        INCLUDE_DIRS "."
        REQUIRES
            esp_driver_gpio
            esp_timer
            nvs_flash
            app_update
            espressif__led_strip
            espressif__esp-zigbee-lib
            jarzem_secure_ota
            status_led_manager
    )
else()
    idf_component_register(
        SRCS
            "app_main.c"
            "debug_console.c"
            "event_bus.c"
            "fatal_error.c"
            "input.c"
            "jarzem_ota_project_hooks.c"
            "power_manager.c"
            "serial_protocol.c"
            "state.c"
            "status_led.c"
            "storage.c"
            "uart_transport.c"
            "zigbee.c"
        INCLUDE_DIRS "."
        REQUIRES
            esp_driver_gpio
            esp_driver_uart
            esp_driver_usb_serial_jtag
            nvs_flash
            app_update
            esp_timer
            esp_pm
            espressif__led_strip
            espressif__esp-zigbee-lib
            jarzem_secure_ota
            status_led_manager
    )
endif()
