#!/usr/bin/env python3
"""
OTA Integration Tests - Run inside OTA add-on container

Tests the existing OTA firmware download against a running OTA server.
No mocking - real HTTPS communication with real firmware.

This test runner is designed to be run INSIDE the Home Assistant OTA add-on container,
where /data/ota_token_secret.bin and the running OTA server are available.
"""

import json
import os
import sys
import ssl
import urllib.request
import urllib.error
from pathlib import Path

# Determine if running in container or locally for development
IN_CONTAINER = os.path.isdir("/data/esp_ota") or os.path.isdir("/share/esp_ota")

# Add parent helper to path
if IN_CONTAINER:
    # In container, assume we're run from /share/esp_ota/tests or similar
    sys.path.insert(0, "/share/esp_ota")
else:
    # Local development
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import ota_helper


class TestResult:
    """Track individual test result."""
    
    def __init__(self, name):
        self.name = name
        self.passed = False
        self.error = None
        self.details = {}
    
    def set_pass(self, **details):
        self.passed = True
        self.details = details
    
    def set_fail(self, error, **details):
        self.passed = False
        self.error = error
        self.details = details
    
    def format_result(self):
        status = "[PASS]" if self.passed else "[FAIL]"
        result = f"{status} {self.name}"
        if self.error:
            result += f"\n  Error: {self.error}"
        return result


class OTATestConfig:
    """OTA test configuration for container or local development."""
    
    def __init__(self):
        if IN_CONTAINER:
            # Running in OTA add-on container
            self.server_host = "localhost"
            self.server_port = 8443
            self.firmware_bin = "/share/esp_ota/firmware/remotecontrol7andEncoder.bin"
            self.firmware_metadata = "/share/esp_ota/firmware/remotecontrol7andEncoder.release.json"
            self.ca_cert = "/share/esp_ota/cert/ota-ca.crt"
            self.server_cert = "/share/esp_ota/cert/ota-server.crt"
            self.token_secret_path = "/data/ota_token_secret.bin"
        else:
            # Local development
            self.server_host = os.environ.get("OTA_SERVER_HOST", "localhost")
            self.server_port = int(os.environ.get("OTA_SERVER_PORT", "8443"))
            project_dir = os.environ.get("OTA_PROJECT_DIR", 
                                        os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
            
            self.firmware_bin = os.path.join(project_dir, "build", "remotecontrol7andEncoder.bin")
            self.firmware_metadata = os.path.join(project_dir, "build", "remotecontrol7andEncoder.release.json")
            self.ca_cert = os.path.join(project_dir, "cert", "ota-ca.crt")
            self.server_cert = os.path.join(project_dir, "cert", "ota-server.crt")
            self.token_secret_path = os.environ.get("OTA_TOKEN_SECRET_PATH", "/data/ota_token_secret.bin")
    
    def validate(self):
        """Check that all required files exist."""
        errors = []
        
        if not os.path.isfile(self.firmware_bin):
            errors.append(f"Firmware BIN not found: {self.firmware_bin}")
        
        if not os.path.isfile(self.firmware_metadata):
            errors.append(f"Firmware metadata not found: {self.firmware_metadata}")
        
        if not os.path.isfile(self.ca_cert):
            errors.append(f"CA certificate not found: {self.ca_cert}")
        
        if not os.path.isfile(self.token_secret_path):
            errors.append(f"Token secret not found: {self.token_secret_path}")
        
        return errors
    
    def __str__(self):
        mode = "CONTAINER" if IN_CONTAINER else "LOCAL"
        return (
            f"OTA Test Config ({mode}):\n"
            f"  Server: https://{self.server_host}:{self.server_port}\n"
            f"  Firmware: {self.firmware_bin}\n"
            f"  Metadata: {self.firmware_metadata}\n"
            f"  CA Cert: {self.ca_cert}\n"
            f"  Token Secret: {self.token_secret_path}"
        )


def load_firmware_metadata(config):
    """Load firmware metadata from release.json."""
    try:
        with open(config.firmware_metadata, "r") as f:
            return json.load(f)
    except Exception as e:
        raise RuntimeError(f"Cannot load firmware metadata: {e}")


def find_firmware_code(config):
    """
    Find the firmware code by probing server.
    
    Tries to GET with each candidate code generated by server algorithm.
    Returns first code that gives 401 (wrong auth) vs 404 (code not found).
    """
    filename = os.path.basename(config.firmware_bin)
    candidates = ota_helper.generate_firmware_code_candidates(filename)
    
    # Create SSL context (skip cert verification for localhost testing)
    ssl_context = ssl.create_default_context()
    ssl_context.check_hostname = False
    ssl_context.verify_mode = ssl.CERT_NONE
    
    for code in candidates:
        url = f"https://{config.server_host}:{config.server_port}/{code}"
        try:
            request = urllib.request.Request(url, method="HEAD")
            with urllib.request.urlopen(request, context=ssl_context) as response:
                # Got 200 without auth
                return code
        except urllib.error.HTTPError as e:
            if e.code == 401:
                # Unauthorized - means code exists but token is invalid. This is our code!
                return code
            elif e.code == 404:
                # Not found - keep trying
                continue
            else:
                raise RuntimeError(f"Unexpected HTTP {e.code}")
        except Exception as e:
            raise RuntimeError(f"Cannot connect to OTA server at {url}: {e}")
    
    raise RuntimeError("Cannot find firmware code - server may not have firmware registered")


def test_ota_firmware_download(config, metadata):
    """Test OTA_FIRMWARE_DOWNLOAD."""
    result = TestResult("OTA_FIRMWARE_DOWNLOAD")
    
    try:
        # Get firmware metadata
        sha256 = metadata.get("sha256")
        size = metadata.get("size")
        
        if not sha256 or not size:
            raise ValueError("Missing sha256 or size in metadata")
        
        # Compute actual SHA256 to verify metadata
        actual_sha256 = ota_helper.compute_firmware_sha256(config.firmware_bin)
        if actual_sha256 != sha256:
            raise ValueError(
                f"SHA256 mismatch: metadata={sha256}, actual={actual_sha256}"
            )
        
        # Find firmware code
        code = find_firmware_code(config)
        
        # Create valid token using shared helper with correct path
        device_id = "aa:bb:cc:dd:ee:ff:00:11"  # Test device ID
        token = ota_helper.create_token(code, device_id, sha256, config.token_secret_path)
        
        # Create SSL context
        ssl_context = ssl.create_default_context()
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE
        
        # Perform GET request
        url = f"https://{config.server_host}:{config.server_port}/{code}"
        request = urllib.request.Request(
            url,
            headers={
                "Authorization": f"Bearer {token}",
                "X-Device-ID": device_id,
            },
            method="GET"
        )
        
        with urllib.request.urlopen(request, context=ssl_context) as response:
            # Check HTTP 200
            if response.status != 200:
                raise AssertionError(f"Expected HTTP 200, got {response.status}")
            
            # Read firmware data
            firmware_data = response.read()
            
            # Check not empty
            if len(firmware_data) == 0:
                raise AssertionError("Firmware data is empty")
            
            # Check size
            if len(firmware_data) != size:
                raise AssertionError(
                    f"Size mismatch: expected {size}, got {len(firmware_data)}"
                )
            
            # Verify SHA256
            downloaded_sha256 = ota_helper.compute_firmware_sha256(firmware_data)
            if downloaded_sha256 != sha256:
                raise AssertionError(
                    f"SHA256 mismatch: expected {sha256}, got {downloaded_sha256}"
                )
            
            # Check X-Firmware-SHA256 header
            server_sha256_header = response.headers.get("X-Firmware-SHA256")
            if server_sha256_header != sha256:
                raise AssertionError(
                    f"Server SHA256 header mismatch: expected {sha256}, got {server_sha256_header}"
                )
        
        result.set_pass(code=code, size=size, sha256=sha256[:12] + "...")
        
    except Exception as e:
        result.set_fail(str(e))
    
    return result


def test_ota_invalid_token_rejected(config, metadata):
    """Test OTA_INVALID_TOKEN_REJECTED."""
    result = TestResult("OTA_INVALID_TOKEN_REJECTED")
    
    try:
        sha256 = metadata.get("sha256")
        code = find_firmware_code(config)
        device_id = "aa:bb:cc:dd:ee:ff:00:11"
        
        # Create invalid token
        invalid_token = "invalid.token.here"
        
        # Create SSL context
        ssl_context = ssl.create_default_context()
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE
        
        url = f"https://{config.server_host}:{config.server_port}/{code}"
        request = urllib.request.Request(
            url,
            headers={
                "Authorization": f"Bearer {invalid_token}",
                "X-Device-ID": device_id,
            },
            method="GET"
        )
        
        try:
            with urllib.request.urlopen(request, context=ssl_context) as response:
                raise AssertionError(f"Expected HTTP 401, got {response.status}")
        except urllib.error.HTTPError as e:
            if e.code != 401:
                raise AssertionError(f"Expected HTTP 401, got {e.code}")
        
        result.set_pass()
        
    except Exception as e:
        result.set_fail(str(e))
    
    return result


def test_ota_missing_device_id_rejected(config, metadata):
    """Test OTA_MISSING_DEVICE_ID_REJECTED."""
    result = TestResult("OTA_MISSING_DEVICE_ID_REJECTED")
    
    try:
        sha256 = metadata.get("sha256")
        code = find_firmware_code(config)
        device_id = "aa:bb:cc:dd:ee:ff:00:11"
        
        # Create valid token
        token = ota_helper.create_token(code, device_id, sha256, config.token_secret_path)
        
        # Create SSL context
        ssl_context = ssl.create_default_context()
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE
        
        url = f"https://{config.server_host}:{config.server_port}/{code}"
        request = urllib.request.Request(
            url,
            headers={
                "Authorization": f"Bearer {token}",
                # NO X-Device-ID header
            },
            method="GET"
        )
        
        try:
            with urllib.request.urlopen(request, context=ssl_context) as response:
                raise AssertionError(f"Expected HTTP 401, got {response.status}")
        except urllib.error.HTTPError as e:
            if e.code != 401:
                raise AssertionError(f"Expected HTTP 401, got {e.code}")
        
        result.set_pass()
        
    except Exception as e:
        result.set_fail(str(e))
    
    return result


def run_all_tests():
    """Run all tests and report results."""
    print()
    print("=" * 70)
    print("OTA Integration Tests")
    print("=" * 70)
    
    # Load config
    config = OTATestConfig()
    print()
    print(config)
    print()
    
    # Validate prerequisites
    errors = config.validate()
    if errors:
        print("✗ PREREQUISITES FAILED:")
        for error in errors:
            print(f"  • {error}")
        print()
        return False
    
    print("✓ All prerequisites met")
    print()
    
    # Load firmware metadata
    try:
        metadata = load_firmware_metadata(config)
    except Exception as e:
        print(f"✗ Cannot load firmware metadata: {e}")
        return False
    
    # Run tests
    results = [
        test_ota_firmware_download(config, metadata),
        test_ota_invalid_token_rejected(config, metadata),
        test_ota_missing_device_id_rejected(config, metadata),
    ]
    
    # Report results
    print()
    for result in results:
        print(result.format_result())
        if result.details:
            for key, value in result.details.items():
                print(f"    {key}: {value}")
    
    print()
    passed = sum(1 for r in results if r.passed)
    failed = sum(1 for r in results if not r.passed)
    
    print(f"Tests: {passed} passed, {failed} failed")
    print()
    
    return failed == 0


if __name__ == "__main__":
    success = run_all_tests()
    sys.exit(0 if success else 1)

